services:
  a_parser_app:
    container_name: a_parser_app
    build:
      dockerfile: ./docker-build/app/Dockerfile
      context: ./
    environment:
      APP_CONFIG__RUN__HOST: "0.0.0.0"
      APP_CONFIG__RUN__PORT: 9889
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
        - action: rebuild
          path: ./poetry.lock
    ports:
      - "9889:9889"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:9889/api/v1/healthcheck/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
